//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 07/21/2020 15:50:12 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace MicroMall.Model.DbModels
{
	/// <summary>
	/// 第三方平台用户授权信息表
	/// </summary>
	public class mall_third_user_info
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int32  Id { get; set;}
		/// <summary>
		/// 昵称
		/// </summary>
		public System.String  NickName { get; set;}
		/// <summary>
		/// 第三方平台用户Id
		/// </summary>
		public System.String  ThirdUserId { get; set;}
		/// <summary>
		/// 性别：1：男 0：女
		/// </summary>
		public System.Int32  Sex { get; set;}=0;
		/// <summary>
		/// 头像
		/// </summary>
		public System.String  Avatar { get; set;}=string.Empty;
		/// <summary>
		/// 联系方式
		/// </summary>
		public System.String  Phone { get; set;}=string.Empty;
		/// <summary>
		/// 来源：1：微信 2：支付宝 依次往后枚举
		/// </summary>
		public System.Int32  Source { get; set;}=0;
		/// <summary>
		/// 用户Uid（自系统）
		/// </summary>
		public System.String  UserUid { get; set;}=string.Empty;
		/// <summary>
		/// 授权时间
		/// </summary>
		public System.DateTime  AuthorizeTime { get; set;}=new DateTime();
	}
}

                