//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 07/21/2020 15:50:12 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace MicroMall.Model.DbModels
{
	/// <summary>
	/// 产品信息表
	/// </summary>
	public class mall_product
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int32  Id { get; set;}
		/// <summary>
		/// 产品简码
		/// </summary>
		public System.String  Code { get; set;}
		/// <summary>
		/// 产品名称
		/// </summary>
		public System.String  Name { get; set;}
		/// <summary>
		/// 单位Id
		/// </summary>
		public System.Int32  UnitId { get; set;}
		/// <summary>
		/// 单位名称
		/// </summary>
		public System.String  UnitName { get; set;}
		/// <summary>
		/// 产品图片地址
		/// </summary>
		public System.String  ImgUrl { get; set;}=string.Empty;
		/// <summary>
		/// 产品描述
		/// </summary>
		public System.String  Description { get; set;}=string.Empty;
		/// <summary>
		/// 分类Id
		/// </summary>
		public System.Int32  CategoryId { get; set;}
		/// <summary>
		/// 排序码
		/// </summary>
		public System.Int32  SortIndex { get; set;}=0;
		/// <summary>
		/// 产品搜索码
		/// </summary>
		public System.String  SearchCode { get; set;}=string.Empty;
		/// <summary>
		/// 状态：0：不可用 1：正常
		/// </summary>
		public System.Int32  Status { get; set;}=0;
		/// <summary>
		/// 集团Id
		/// </summary>
		public System.Int32  GroupId { get; set;}
		/// <summary>
		/// 创建日期
		/// </summary>
		public System.DateTime  CreateTime { get; set;}=new DateTime();
	}
}

                