//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 07/21/2020 15:50:12 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace MicroMall.Model.DbModels
{
	/// <summary>
	/// 企业信息表
	/// </summary>
	public class mall_company
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int32  Id { get; set;}
		/// <summary>
		/// 企业名称
		/// </summary>
		public System.String  CompanyName { get; set;}
		/// <summary>
		/// 用户名
		/// </summary>
		public System.String  UserName { get; set;}
		/// <summary>
		/// 密码
		/// </summary>
		public System.String  PassWord { get; set;}
		/// <summary>
		/// 所在区域（区县Code）
		/// </summary>
		public System.Int32  AreaId { get; set;}=0;
		/// <summary>
		/// 法人
		/// </summary>
		public System.String  LegalPerson { get; set;}=string.Empty;
		/// <summary>
		/// 电话
		/// </summary>
		public System.String  Phone { get; set;}=string.Empty;
		/// <summary>
		/// 传真
		/// </summary>
		public System.String  Fax { get; set;}=string.Empty;
		/// <summary>
		/// 详细地址
		/// </summary>
		public System.String  Address { get; set;}=string.Empty;
		/// <summary>
		/// 联系人
		/// </summary>
		public System.String  Relation { get; set;}
		/// <summary>
		/// 联系人电话
		/// </summary>
		public System.String  RelationPhone { get; set;}
		/// <summary>
		/// 开户行名称
		/// </summary>
		public System.String  BankName { get; set;}=string.Empty;
		/// <summary>
		/// 银行卡号
		/// </summary>
		public System.String  BankNumber { get; set;}=string.Empty;
		/// <summary>
		/// 邮政编码
		/// </summary>
		public System.String  PostCode { get; set;}=string.Empty;
		/// <summary>
		/// 上级Id
		/// </summary>
		public System.Int32  ParentId { get; set;}=0;
		/// <summary>
		/// 唯一编码
		/// </summary>
		public System.String  UniqueCode { get; set;}
		/// <summary>
		/// 是否可用，1：可用 0：停用
		/// </summary>
		public System.Int32  Status { get; set;}=0;
		/// <summary>
		/// 创建日期
		/// </summary>
		public System.DateTime  CreateDate { get; set;}
		/// <summary>
		/// 修改日期
		/// </summary>
		public System.DateTime  ModifyDate { get; set;}
		/// <summary>
		/// 备注
		/// </summary>
		public System.String  Remark { get; set;}=string.Empty;
	}
}

                