  


//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 07/21/2020 15:50:12 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace MicroMall.Model.DbModels
{
	/// <summary>
	/// 产品分类表
	/// </summary>
	public class mall_category
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int32  Id { get; set;}
		/// <summary>
		/// 分类名称
		/// </summary>
		public System.String  Name { get; set;}
		/// <summary>
		/// 排序码
		/// </summary>
		public System.Int32  SortIndex { get; set;}
		/// <summary>
		/// 父Id
		/// </summary>
		public System.Int32  ParentId { get; set;}=0;
		/// <summary>
		/// 1：一级分类 2:二级分类
		/// </summary>
		public System.Int32  Deep { get; set;}=0;
		/// <summary>
		/// 集团id
		/// </summary>
		public System.Int32  GroupId { get; set;}
	}
}

                